# ── External validator ────────────────────────────────────────────────────────
EXTERNAL_SCRIPT := external/guide_rna_sequences_check.py
EXTERNAL_URL    := https://raw.githubusercontent.com/IGVF-DACC/checkfiles/dev/src/checkfiles/guide_rna_sequences_check.py

# Fetch the latest version of the IGVF-DACC external validator
update-external:
	@echo "Fetching latest $(EXTERNAL_SCRIPT) from IGVF-DACC/checkfiles …"
	curl -fsSL "$(EXTERNAL_URL)" -o "$(EXTERNAL_SCRIPT).new"
	@# Prepend the vendoring header, then replace the file
	@python3 -c "\
import re, sys, datetime; \
content = open('$(EXTERNAL_SCRIPT).new').read(); \
sha_line = '# Last updated from commit: (run make update-external to refresh)'; \
header = '# Vendored from IGVF-DACC/checkfiles (dev branch)\n# Source: https://github.com/IGVF-DACC/checkfiles/blob/dev/src/checkfiles/guide_rna_sequences_check.py\n# Last updated: ' + str(datetime.date.today()) + '\n#\n# To update to the latest version:\n#   make update-external\n#\n# DO NOT EDIT THIS FILE MANUALLY — it is managed by update-external.\n\n'; \
open('$(EXTERNAL_SCRIPT)', 'w').write(header + content)"
	@rm -f "$(EXTERNAL_SCRIPT).new"
	@echo "Done. Review git diff external/ before committing."

# ── Validation helpers ────────────────────────────────────────────────────────

# Run both our validator and the IGVF-DACC external check on a file.
# Usage: make validate FILE=output/IGVFFI0580WJFK.tsv.gz
validate:
	@if [ -z "$(FILE)" ]; then \
		echo "Usage: make validate FILE=output/IGVFFIXXXXXXXX.tsv.gz"; exit 1; fi
	python3 validate_grna_file.py "$(FILE)"
	python3 run_external_check.py "$(FILE)"

# Run both validators on ALL files in output/
validate-all:
	@for f in output/*.tsv.gz; do \
		echo ""; \
		python3 validate_grna_file.py "$$f"; \
		python3 run_external_check.py "$$f"; \
	done

# ── Tests ─────────────────────────────────────────────────────────────────────

test:
	python3 -m pytest tests/ -v

.PHONY: update-external validate validate-all test
